name: Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  old_otp_version_tests:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: '1.10'
            otp: '22'
          - elixir: '1.10'
            otp: '23'
          - elixir: '1.11'
            otp: '22'
          - elixir: '1.11'
            otp: '23'
          - elixir: '1.12'
            otp: '22'
          - elixir: '1.12'
            otp: '23'
          - elixir: '1.13'
            otp: '22'
          - elixir: '1.13'
            otp: '23'
          - elixir: '1.14'
            otp: '23'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test

  version_tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: '1.11'
            otp: '24'
          - elixir: '1.12'
            otp: '24'
          - elixir: '1.13'
            otp: '24'
          - elixir: '1.13'
            otp: '25'
          - elixir: '1.14'
            otp: '24'
          - elixir: '1.14'
            otp: '25'
          - elixir: '1.14'
            otp: '26'
          - elixir: '1.15'
            otp: '24'
          - elixir: '1.15'
            otp: '25'
          - elixir: '1.15'
            otp: '26'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test

  all_versions_tests:
    name: "All Versions Tests"
    needs: [old_otp_version_tests, version_tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Elixir tests for many versions of Elixir and OTP have successfully completed."

  poison_only_test:
    runs-on: ubuntu-20.04
    name: Test - poison only, no jason
    defaults:
      run:
        working-directory: integration_test_apps/poison_only_app
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.15'
      - run: mix deps.get
      - run: mix test

  jason_only_test:
    runs-on: ubuntu-20.04
    name: Test - jason only, no poison
    defaults:
      run:
        working-directory: integration_test_apps/jason_only_app
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.15'
      - run: mix deps.get
      - run: mix test

  all_tests:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: '1.15.6'
            otp: '26.1.1'
    steps:
      - uses: actions/checkout@v4
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Get Deps
        run: mix deps.get

      - name: Cache Elixir build
        uses: actions/cache@v3
        with:
          path: _build
          key: elixir-build-v1-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('lib/**/*.ex', 'config/*.exs', 'mix.exs') }}

      - name: Compile Deps
        run: mix deps.compile

      - name: Compiler Warnings
        run: mix compile --force --warnings-as-errors

      - name: Run Credo
        run: mix credo --strict

      - name: Check Format
        run: mix format --check-formatted

      - name: Run Coveralls
        run: mix coveralls

      - name: Generate Docs
        run: mix docs --output test/doc

      - name: Run Dialyzer
        run: mix dialyzer --list-unused-filters

  required_all_tests:
    name: "Complete Elixir Tests"
    needs: [all_tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Elixir tests and static analyses completed succcessfully."
