name: Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  version_tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: '1.10'
            otp: '22'
          - elixir: '1.11'
            otp: '22'
          - elixir: '1.12'
            otp: '22'
          - elixir: '1.10'
            otp: '23'
          - elixir: '1.11'
            otp: '23'
          - elixir: '1.12'
            otp: '23'
          # SKIP: Elixir 1.10, OTP 24
          - elixir: '1.11'
            otp: '24'
          - elixir: '1.12'
            otp: '24'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test

  poison_only_test:
    runs-on: ubuntu-latest
    name: Test - poison only, no jason
    defaults:
      run:
        working-directory: integration_test_apps/poison_only_app
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.11'
      - run: mix deps.get
      - run: mix test

  jason_only_test:
    runs-on: ubuntu-latest
    name: Test - jason only, no poison
    defaults:
      run:
        working-directory: integration_test_apps/jason_only_app
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.11'
      - run: mix deps.get
      - run: mix test


  all_tests:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: '1.11.4'
            otp: '23.3.1'
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Get Deps
        run: mix deps.get

      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: _build
          key: elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('lib/**/*.ex', 'config/*.exs', 'mix.exs') }}
          restore-keys: |
            elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-
            elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Compile Deps
        run: mix deps.compile

      - name: Compiler Warnings
        run: mix compile --force --warnings-as-errors

      - name: Run Credo
        run: mix credo --strict

      - name: Check Format
        run: mix format --check-formatted

      - name: Run Coveralls
        run: mix coveralls

      - name: Generate Docs
        run: mix docs --output test/doc

      - name: Run Dialyzer
        run: mix dialyzer --list-unused-filters
